images:
  genaiService:
    repository: lam1312200/spring-petclinic-genai-service
    tag: latest
  adminServer:
    repository: lam1312200/spring-petclinic-admin-server
    tag: latest
  customersService:
    repository: lam1312200/spring-petclinic-customers-service
    tag: latest
  vetsService:
    repository: lam1312200/spring-petclinic-vets-service
    tag: latest
  visitsService:
    repository: lam1312200/spring-petclinic-visits-service
    tag: latest
  apiGateway:
    repository: lam1312200/spring-petclinic-api-gateway
    tag: latest
  discoveryServer:
    repository: lam1312200/spring-petclinic-discovery-server
    tag: latest
  configServer:
    repository: lam1312200/spring-petclinic-config-server
    tag: latest
  tracingServer:
    repository: lam1312200/zipkin-server
    tag: latest

imagePullSecrets:
  name: regcred

config:
  discoveryServer:
    url: http://discovery-server:8761
  configServer:
    url: http://config-server:8888

hostname:
  genaiService:
    name: genai-service
  adminServer:
    name: admin-server
  customersService:
    name: customers-service
  vetsService:
    name: vets-service
  visitsService:
    name: visits-service
  apiGateway:
    name: api-gateway
  discoveryServer:
    name: discovery-server
  configServer:
    name: config-server
  tracingServer:
    name: tracing-server
